apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: embedding-api
  labels:
    app: embedding
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: embedding
        tier: frontend
    spec:
      containers:
      - name: embedding-api
        # Replace [GCLOUD_PROJECT] with your project ID or use `make template`.
        image: gcr.io/[GCLOUD_PROJECT]/embedding-api
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 5000
